
IF (NOT EXISTS ${DSL_DIRECTORY})
	execute_process(COMMAND git clone https://github.com/DriftSolutions/DSL.git "${DSL_DIRECTORY}")
ENDIF()
IF (NOT EXISTS ${DSL_DIRECTORY})
        message(FATAL_ERROR "Could not clone the DSL repository!")
ENDIF()

AUX_SOURCE_DIRECTORY(${DSL_DIRECTORY}/src SRCFILES)
AUX_SOURCE_DIRECTORY(${DSL_DIRECTORY}/src/algo ALGOFILES)
AUX_SOURCE_DIRECTORY(${DSL_DIRECTORY}/src/libevent EVENTFILES)

add_library (ibdsl STATIC ${SRCFILES} ${ALGOFILES} ${EVENTFILES})
SET_TARGET_PROPERTIES(ibdsl PROPERTIES ARCHIVE_OUTPUT_DIRECTORY ../../obj)
